use cs;
select * from customer;

ALTER TABLE customer 
CHANGE `purchase_amount_(usd)` purchase_amount INT;


#Q1. What is the total revenue generated by male vs. female customers?
select gender, sum(purchase_amount) as revenue
from customer
group by gender;

# Which customers used a discount but still spent more than the average purchase amount? 
select customer_id,purchase_amount
from customer
where discount_applied='yes' and purchase_amount>=(select AVG(purchase_amount) from customer)

#Q3. Which are the top 5 products with the highest average review rating?
SELECT 
    ROUND(AVG(review_rating), 2) AS `AVG Rating`,
    item_purchased
FROM customer
GROUP BY item_purchased
ORDER BY AVG(review_rating) DESC
LIMIT 5;

#Compare the average Purchase Amounts between Standard and Express Shipping.
select AVG(purchase_amount),shipping_type
from customer
where shipping_type IN('Express','Standard')
group by shipping_type;

/*Do subscribed customers spend more? Compare average spend and total revenue 
between subscribers and non-subscribers*/
SELECT 
    subscription_status,
    COUNT(customer_id) AS total_customers,
    ROUND(AVG(purchase_amount), 2) AS avg_spend,
    ROUND(SUM(purchase_amount), 2) AS total_revenue
FROM customer
GROUP BY subscription_status
ORDER BY total_revenue DESC, avg_spend DESC;

# Which 5 products have the highest percentage of purchases with discounts applied?
SELECT 
    item_purchased,
    ROUND(
        (SUM(CASE WHEN discount_applied = 'yes' THEN 1 ELSE 0 END) / COUNT(*)) * 100,
        2
    ) AS discount_rate
FROM customer
GROUP BY item_purchased
ORDER BY discount_rate DESC
LIMIT 5;

/*Segment customers into New, Returning, and Loyal based on their total 
-- number of previous purchases, and show the count of each segment.*/
with customer_type as (
select customer_id,previous_purchases,
case
	when previous_purchases =1 then 'NEW'
    when previous_purchases between 2 and 10 then 'Returning'
    else 'loyal'
    end as customer_segment
from customer
)
select customer_segment, count(*) as "num of customers"
from customer_type
group by customer_segment

#What are the top 3 most purchased products within each category? 

with item_counts as(
select category,item_purchased,
count(customer_id) as total_orders,
row_number() over (partition by category order by count(customer_id) desc ) as item_rank
from customer
group by category,item_purchased
)
select item_rank,category,item_purchased,total_orders
from item_counts
where item_rank<=3;

# Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
select subscription_status,
count(customer_id) as repeat_buyers
from customer
where previous_purchases >5
group by subscription_status

#What is the revenue contribution of each age group?
select age_group,sum(purchase_amount) as total_revenue
from customer
group by age_group
order by total_revenue desc;






